import FramerMotionWrapper from "@/Motion/FramerMotionWrapper";
import "./globals.css";
import type { Metadata } from "next";
import MotionMouse from "@/Motion/Mouse";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={` relative`}>
				<FramerMotionWrapper>
					<MotionMouse />
					{children}
				</FramerMotionWrapper>
				<div id="magnetize" className="absolute pointer-events-none top-0 left-0 w-screen h-screen"></div>
			</body>
		</html>
	);
}
